### ISSUE TITLE
路由表的构造形式疑问

### ISSUE THREAD

**Issue by BCsl** [kyleduo/Rabbits#1]
路由表需要从 `json` 文件中解析，这种方式来管理虽然可能使得路由看起来更清晰，但毕竟是耗时操作，即使提供了异步的方式来加载，还是有些小顾虑，不知道作者是怎么看待这个问题的？是处于什么目的这样设计？是为了能够动态更新路由表吗？另外路由表的更新有什么使用场景？

**Comment by kyleduo** [comment]
首先你的疑问是有道理的，涉及到io确实是耗时操作，但是你也提到了，是可以用异步处理的，所以不会阻塞主线程。如果你担心会影响启动速度，也可以在界面显示出来之后进行加载，比如启动页倒计时的时候，只要在使用之前进行初始化即可。
至于为什么这么设计，一方面是为了保证能动态更新，另一方面也是为了统一管理。目前一些框架把路由表分散到项目的各个地方，查找和管理都比较麻烦，也容易出错。至于更新的场景，需求无关的比如A/B Test、功能降级等都可以支持；涉及到运营和产品需求的，那就五花八门了。
不知道是否解决了你的疑问。

**Comment by BCsl** [comment]
恩，统一管理的确会比较清晰，我的担忧是会有可能在还没初始化还没完成的时候就进行页面的跳转了

**Comment by kyleduo** [comment]
这个问题确实存在，如果异步初始化，要做防御逻辑。所以如果没有特别的要求，还是建议使用同步初始化。

**Comment by BCsl** [comment]
谢谢解答
