### ISSUE TITLE
使用MultiDex的问题

### ISSUE THREAD

**Issue by shouzhong** [kyleduo/Rabbits#2]
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/kyleduo/rabbits/P;

**Comment by kyleduo** [comment]
项目中有多个module吗

**Comment by shouzhong** [comment]
是的，有没有什么解决办法吗

**Comment by kyleduo** [comment]
多个module都使用Rabbits的时候，需要在build.gradle里面配置module name（子module），看下正确配置了吗？https://github.com/kyleduo/Rabbits/wiki/Multiple-Module
